version: "3.8"
services:
  db:
    container_name: plugin_server_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root # will not be used in prod
      - POSTGRES_DB=PluginServerDB
    ports:
      - "5678:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data/


volumes:
  postgres-data:

