// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/Encedeus/pluginServer/ent/plugin"
	"github.com/Encedeus/pluginServer/ent/publication"
	"github.com/Encedeus/pluginServer/ent/schema"
	"github.com/Encedeus/pluginServer/ent/user"
	"github.com/Encedeus/pluginServer/ent/verificationsession"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescID is the schema descriptor for id field.
	pluginDescID := pluginFields[0].Descriptor()
	// plugin.DefaultID holds the default value on creation for the id field.
	plugin.DefaultID = pluginDescID.Default.(func() uuid.UUID)
	publicationFields := schema.Publication{}.Fields()
	_ = publicationFields
	// publicationDescCreatedAt is the schema descriptor for created_at field.
	publicationDescCreatedAt := publicationFields[0].Descriptor()
	// publication.DefaultCreatedAt holds the default value on creation for the created_at field.
	publication.DefaultCreatedAt = publicationDescCreatedAt.Default.(func() time.Time)
	// publicationDescIsDeprecated is the schema descriptor for is_deprecated field.
	publicationDescIsDeprecated := publicationFields[1].Descriptor()
	// publication.DefaultIsDeprecated holds the default value on creation for the is_deprecated field.
	publication.DefaultIsDeprecated = publicationDescIsDeprecated.Default.(bool)
	// publicationDescName is the schema descriptor for name field.
	publicationDescName := publicationFields[2].Descriptor()
	// publication.NameValidator is a validator for the "name" field. It is called by the builders before save.
	publication.NameValidator = publicationDescName.Validators[0].(func(string) error)
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
	user.Hooks[1] = userHooks[1]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescAuthUpdatedAt is the schema descriptor for auth_updated_at field.
	userDescAuthUpdatedAt := userFields[3].Descriptor()
	// user.DefaultAuthUpdatedAt holds the default value on creation for the auth_updated_at field.
	user.DefaultAuthUpdatedAt = userDescAuthUpdatedAt.Default.(func() time.Time)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[5].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[7].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmailVerified is the schema descriptor for email_verified field.
	userDescEmailVerified := userFields[8].Descriptor()
	// user.DefaultEmailVerified holds the default value on creation for the email_verified field.
	user.DefaultEmailVerified = userDescEmailVerified.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	verificationsessionFields := schema.VerificationSession{}.Fields()
	_ = verificationsessionFields
	// verificationsessionDescID is the schema descriptor for id field.
	verificationsessionDescID := verificationsessionFields[0].Descriptor()
	// verificationsession.DefaultID holds the default value on creation for the id field.
	verificationsession.DefaultID = verificationsessionDescID.Default.(func() string)
}

const (
	Version = "v0.12.4"                                         // Version of ent codegen.
	Sum     = "h1:LddPnAyxls/O7DTXZvUGDj0NZIdGSu317+aoNLJWbD8=" // Sum of ent codegen.
)
