// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PluginsColumns holds the columns for the "plugins" table.
	PluginsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "repo", Type: field.TypeString, Nullable: true},
		{Name: "homepage", Type: field.TypeString, Nullable: true},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "contributors", Type: field.TypeJSON},
	}
	// PluginsTable holds the schema information for the "plugins" table.
	PluginsTable = &schema.Table{
		Name:       "plugins",
		Columns:    PluginsColumns,
		PrimaryKey: []*schema.Column{PluginsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "auth_updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 32},
		{Name: "password", Type: field.TypeString},
		{Name: "verified", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VerifySessionsColumns holds the columns for the "verify_sessions" table.
	VerifySessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "sid", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// VerifySessionsTable holds the schema information for the "verify_sessions" table.
	VerifySessionsTable = &schema.Table{
		Name:       "verify_sessions",
		Columns:    VerifySessionsColumns,
		PrimaryKey: []*schema.Column{VerifySessionsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PluginsTable,
		UsersTable,
		VerifySessionsTable,
	}
)

func init() {
}
