// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PluginServer/ent/plugin"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PluginCreate is the builder for creating a Plugin entity.
type PluginCreate struct {
	config
	mutation *PluginMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (pc *PluginCreate) SetCreatedAt(t time.Time) *PluginCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PluginCreate) SetNillableCreatedAt(t *time.Time) *PluginCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PluginCreate) SetUpdatedAt(t time.Time) *PluginCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PluginCreate) SetNillableUpdatedAt(t *time.Time) *PluginCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetName sets the "name" field.
func (pc *PluginCreate) SetName(s string) *PluginCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetDescription sets the "description" field.
func (pc *PluginCreate) SetDescription(s string) *PluginCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pc *PluginCreate) SetNillableDescription(s *string) *PluginCreate {
	if s != nil {
		pc.SetDescription(*s)
	}
	return pc
}

// SetRepo sets the "repo" field.
func (pc *PluginCreate) SetRepo(s string) *PluginCreate {
	pc.mutation.SetRepo(s)
	return pc
}

// SetNillableRepo sets the "repo" field if the given value is not nil.
func (pc *PluginCreate) SetNillableRepo(s *string) *PluginCreate {
	if s != nil {
		pc.SetRepo(*s)
	}
	return pc
}

// SetHomepage sets the "homepage" field.
func (pc *PluginCreate) SetHomepage(s string) *PluginCreate {
	pc.mutation.SetHomepage(s)
	return pc
}

// SetNillableHomepage sets the "homepage" field if the given value is not nil.
func (pc *PluginCreate) SetNillableHomepage(s *string) *PluginCreate {
	if s != nil {
		pc.SetHomepage(*s)
	}
	return pc
}

// SetOwnerID sets the "owner_id" field.
func (pc *PluginCreate) SetOwnerID(u uuid.UUID) *PluginCreate {
	pc.mutation.SetOwnerID(u)
	return pc
}

// SetContributors sets the "contributors" field.
func (pc *PluginCreate) SetContributors(s []string) *PluginCreate {
	pc.mutation.SetContributors(s)
	return pc
}

// Mutation returns the PluginMutation object of the builder.
func (pc *PluginCreate) Mutation() *PluginMutation {
	return pc.mutation
}

// Save creates the Plugin in the database.
func (pc *PluginCreate) Save(ctx context.Context) (*Plugin, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PluginCreate) SaveX(ctx context.Context) *Plugin {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PluginCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PluginCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PluginCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := plugin.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := plugin.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PluginCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Plugin.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Plugin.updated_at"`)}
	}
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Plugin.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := plugin.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plugin.name": %w`, err)}
		}
	}
	if v, ok := pc.mutation.Description(); ok {
		if err := plugin.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Plugin.description": %w`, err)}
		}
	}
	if _, ok := pc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Plugin.owner_id"`)}
	}
	if _, ok := pc.mutation.Contributors(); !ok {
		return &ValidationError{Name: "contributors", err: errors.New(`ent: missing required field "Plugin.contributors"`)}
	}
	return nil
}

func (pc *PluginCreate) sqlSave(ctx context.Context) (*Plugin, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PluginCreate) createSpec() (*Plugin, *sqlgraph.CreateSpec) {
	var (
		_node = &Plugin{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(plugin.Table, sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.SetField(plugin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.SetField(plugin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(plugin.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(plugin.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := pc.mutation.Repo(); ok {
		_spec.SetField(plugin.FieldRepo, field.TypeString, value)
		_node.Repo = value
	}
	if value, ok := pc.mutation.Homepage(); ok {
		_spec.SetField(plugin.FieldHomepage, field.TypeString, value)
		_node.Homepage = value
	}
	if value, ok := pc.mutation.OwnerID(); ok {
		_spec.SetField(plugin.FieldOwnerID, field.TypeUUID, value)
		_node.OwnerID = value
	}
	if value, ok := pc.mutation.Contributors(); ok {
		_spec.SetField(plugin.FieldContributors, field.TypeJSON, value)
		_node.Contributors = value
	}
	return _node, _spec
}

// PluginCreateBulk is the builder for creating many Plugin entities in bulk.
type PluginCreateBulk struct {
	config
	builders []*PluginCreate
}

// Save creates the Plugin entities in the database.
func (pcb *PluginCreateBulk) Save(ctx context.Context) ([]*Plugin, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Plugin, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PluginCreateBulk) SaveX(ctx context.Context) []*Plugin {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PluginCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PluginCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
