// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Encedeus/pluginServer/ent/predicate"
	"github.com/Encedeus/pluginServer/ent/user"
	"github.com/Encedeus/pluginServer/ent/verificationsession"
	"github.com/google/uuid"
)

// VerificationSessionQuery is the builder for querying VerificationSession entities.
type VerificationSessionQuery struct {
	config
	ctx         *QueryContext
	order       []verificationsession.OrderOption
	inters      []Interceptor
	predicates  []predicate.VerificationSession
	withSession *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VerificationSessionQuery builder.
func (vsq *VerificationSessionQuery) Where(ps ...predicate.VerificationSession) *VerificationSessionQuery {
	vsq.predicates = append(vsq.predicates, ps...)
	return vsq
}

// Limit the number of records to be returned by this query.
func (vsq *VerificationSessionQuery) Limit(limit int) *VerificationSessionQuery {
	vsq.ctx.Limit = &limit
	return vsq
}

// Offset to start from.
func (vsq *VerificationSessionQuery) Offset(offset int) *VerificationSessionQuery {
	vsq.ctx.Offset = &offset
	return vsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vsq *VerificationSessionQuery) Unique(unique bool) *VerificationSessionQuery {
	vsq.ctx.Unique = &unique
	return vsq
}

// Order specifies how the records should be ordered.
func (vsq *VerificationSessionQuery) Order(o ...verificationsession.OrderOption) *VerificationSessionQuery {
	vsq.order = append(vsq.order, o...)
	return vsq
}

// QuerySession chains the current query on the "session" edge.
func (vsq *VerificationSessionQuery) QuerySession() *UserQuery {
	query := (&UserClient{config: vsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(verificationsession.Table, verificationsession.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, verificationsession.SessionTable, verificationsession.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(vsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VerificationSession entity from the query.
// Returns a *NotFoundError when no VerificationSession was found.
func (vsq *VerificationSessionQuery) First(ctx context.Context) (*VerificationSession, error) {
	nodes, err := vsq.Limit(1).All(setContextOp(ctx, vsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{verificationsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vsq *VerificationSessionQuery) FirstX(ctx context.Context) *VerificationSession {
	node, err := vsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VerificationSession ID from the query.
// Returns a *NotFoundError when no VerificationSession ID was found.
func (vsq *VerificationSessionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = vsq.Limit(1).IDs(setContextOp(ctx, vsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{verificationsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vsq *VerificationSessionQuery) FirstIDX(ctx context.Context) string {
	id, err := vsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VerificationSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VerificationSession entity is found.
// Returns a *NotFoundError when no VerificationSession entities are found.
func (vsq *VerificationSessionQuery) Only(ctx context.Context) (*VerificationSession, error) {
	nodes, err := vsq.Limit(2).All(setContextOp(ctx, vsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{verificationsession.Label}
	default:
		return nil, &NotSingularError{verificationsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vsq *VerificationSessionQuery) OnlyX(ctx context.Context) *VerificationSession {
	node, err := vsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VerificationSession ID in the query.
// Returns a *NotSingularError when more than one VerificationSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (vsq *VerificationSessionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = vsq.Limit(2).IDs(setContextOp(ctx, vsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{verificationsession.Label}
	default:
		err = &NotSingularError{verificationsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vsq *VerificationSessionQuery) OnlyIDX(ctx context.Context) string {
	id, err := vsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VerificationSessions.
func (vsq *VerificationSessionQuery) All(ctx context.Context) ([]*VerificationSession, error) {
	ctx = setContextOp(ctx, vsq.ctx, "All")
	if err := vsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VerificationSession, *VerificationSessionQuery]()
	return withInterceptors[[]*VerificationSession](ctx, vsq, qr, vsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vsq *VerificationSessionQuery) AllX(ctx context.Context) []*VerificationSession {
	nodes, err := vsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VerificationSession IDs.
func (vsq *VerificationSessionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if vsq.ctx.Unique == nil && vsq.path != nil {
		vsq.Unique(true)
	}
	ctx = setContextOp(ctx, vsq.ctx, "IDs")
	if err = vsq.Select(verificationsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vsq *VerificationSessionQuery) IDsX(ctx context.Context) []string {
	ids, err := vsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vsq *VerificationSessionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vsq.ctx, "Count")
	if err := vsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vsq, querierCount[*VerificationSessionQuery](), vsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vsq *VerificationSessionQuery) CountX(ctx context.Context) int {
	count, err := vsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vsq *VerificationSessionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vsq.ctx, "Exist")
	switch _, err := vsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vsq *VerificationSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := vsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VerificationSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vsq *VerificationSessionQuery) Clone() *VerificationSessionQuery {
	if vsq == nil {
		return nil
	}
	return &VerificationSessionQuery{
		config:      vsq.config,
		ctx:         vsq.ctx.Clone(),
		order:       append([]verificationsession.OrderOption{}, vsq.order...),
		inters:      append([]Interceptor{}, vsq.inters...),
		predicates:  append([]predicate.VerificationSession{}, vsq.predicates...),
		withSession: vsq.withSession.Clone(),
		// clone intermediate query.
		sql:  vsq.sql.Clone(),
		path: vsq.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (vsq *VerificationSessionQuery) WithSession(opts ...func(*UserQuery)) *VerificationSessionQuery {
	query := (&UserClient{config: vsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	vsq.withSession = query
	return vsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VerificationSession.Query().
//		GroupBy(verificationsession.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vsq *VerificationSessionQuery) GroupBy(field string, fields ...string) *VerificationSessionGroupBy {
	vsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VerificationSessionGroupBy{build: vsq}
	grbuild.flds = &vsq.ctx.Fields
	grbuild.label = verificationsession.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.VerificationSession.Query().
//		Select(verificationsession.FieldUserID).
//		Scan(ctx, &v)
func (vsq *VerificationSessionQuery) Select(fields ...string) *VerificationSessionSelect {
	vsq.ctx.Fields = append(vsq.ctx.Fields, fields...)
	sbuild := &VerificationSessionSelect{VerificationSessionQuery: vsq}
	sbuild.label = verificationsession.Label
	sbuild.flds, sbuild.scan = &vsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VerificationSessionSelect configured with the given aggregations.
func (vsq *VerificationSessionQuery) Aggregate(fns ...AggregateFunc) *VerificationSessionSelect {
	return vsq.Select().Aggregate(fns...)
}

func (vsq *VerificationSessionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vsq); err != nil {
				return err
			}
		}
	}
	for _, f := range vsq.ctx.Fields {
		if !verificationsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vsq.path != nil {
		prev, err := vsq.path(ctx)
		if err != nil {
			return err
		}
		vsq.sql = prev
	}
	return nil
}

func (vsq *VerificationSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VerificationSession, error) {
	var (
		nodes       = []*VerificationSession{}
		_spec       = vsq.querySpec()
		loadedTypes = [1]bool{
			vsq.withSession != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VerificationSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VerificationSession{config: vsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := vsq.withSession; query != nil {
		if err := vsq.loadSession(ctx, query, nodes, nil,
			func(n *VerificationSession, e *User) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (vsq *VerificationSessionQuery) loadSession(ctx context.Context, query *UserQuery, nodes []*VerificationSession, init func(*VerificationSession), assign func(*VerificationSession, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*VerificationSession)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (vsq *VerificationSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vsq.querySpec()
	_spec.Node.Columns = vsq.ctx.Fields
	if len(vsq.ctx.Fields) > 0 {
		_spec.Unique = vsq.ctx.Unique != nil && *vsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vsq.driver, _spec)
}

func (vsq *VerificationSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(verificationsession.Table, verificationsession.Columns, sqlgraph.NewFieldSpec(verificationsession.FieldID, field.TypeString))
	_spec.From = vsq.sql
	if unique := vsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vsq.path != nil {
		_spec.Unique = true
	}
	if fields := vsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verificationsession.FieldID)
		for i := range fields {
			if fields[i] != verificationsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if vsq.withSession != nil {
			_spec.Node.AddColumnOnce(verificationsession.FieldUserID)
		}
	}
	if ps := vsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vsq *VerificationSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vsq.driver.Dialect())
	t1 := builder.Table(verificationsession.Table)
	columns := vsq.ctx.Fields
	if len(columns) == 0 {
		columns = verificationsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vsq.sql != nil {
		selector = vsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vsq.ctx.Unique != nil && *vsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vsq.predicates {
		p(selector)
	}
	for _, p := range vsq.order {
		p(selector)
	}
	if offset := vsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VerificationSessionGroupBy is the group-by builder for VerificationSession entities.
type VerificationSessionGroupBy struct {
	selector
	build *VerificationSessionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vsgb *VerificationSessionGroupBy) Aggregate(fns ...AggregateFunc) *VerificationSessionGroupBy {
	vsgb.fns = append(vsgb.fns, fns...)
	return vsgb
}

// Scan applies the selector query and scans the result into the given value.
func (vsgb *VerificationSessionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vsgb.build.ctx, "GroupBy")
	if err := vsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VerificationSessionQuery, *VerificationSessionGroupBy](ctx, vsgb.build, vsgb, vsgb.build.inters, v)
}

func (vsgb *VerificationSessionGroupBy) sqlScan(ctx context.Context, root *VerificationSessionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vsgb.fns))
	for _, fn := range vsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vsgb.flds)+len(vsgb.fns))
		for _, f := range *vsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VerificationSessionSelect is the builder for selecting fields of VerificationSession entities.
type VerificationSessionSelect struct {
	*VerificationSessionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vss *VerificationSessionSelect) Aggregate(fns ...AggregateFunc) *VerificationSessionSelect {
	vss.fns = append(vss.fns, fns...)
	return vss
}

// Scan applies the selector query and scans the result into the given value.
func (vss *VerificationSessionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vss.ctx, "Select")
	if err := vss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VerificationSessionQuery, *VerificationSessionSelect](ctx, vss.VerificationSessionQuery, vss, vss.inters, v)
}

func (vss *VerificationSessionSelect) sqlScan(ctx context.Context, root *VerificationSessionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vss.fns))
	for _, fn := range vss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
