// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Encedeus/pluginServer/ent/user"
	"github.com/Encedeus/pluginServer/ent/verificationsession"
	"github.com/google/uuid"
)

// VerificationSessionCreate is the builder for creating a VerificationSession entity.
type VerificationSessionCreate struct {
	config
	mutation *VerificationSessionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (vsc *VerificationSessionCreate) SetUserID(u uuid.UUID) *VerificationSessionCreate {
	vsc.mutation.SetUserID(u)
	return vsc
}

// SetID sets the "id" field.
func (vsc *VerificationSessionCreate) SetID(s string) *VerificationSessionCreate {
	vsc.mutation.SetID(s)
	return vsc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (vsc *VerificationSessionCreate) SetNillableID(s *string) *VerificationSessionCreate {
	if s != nil {
		vsc.SetID(*s)
	}
	return vsc
}

// SetSessionID sets the "session" edge to the User entity by ID.
func (vsc *VerificationSessionCreate) SetSessionID(id uuid.UUID) *VerificationSessionCreate {
	vsc.mutation.SetSessionID(id)
	return vsc
}

// SetSession sets the "session" edge to the User entity.
func (vsc *VerificationSessionCreate) SetSession(u *User) *VerificationSessionCreate {
	return vsc.SetSessionID(u.ID)
}

// Mutation returns the VerificationSessionMutation object of the builder.
func (vsc *VerificationSessionCreate) Mutation() *VerificationSessionMutation {
	return vsc.mutation
}

// Save creates the VerificationSession in the database.
func (vsc *VerificationSessionCreate) Save(ctx context.Context) (*VerificationSession, error) {
	vsc.defaults()
	return withHooks(ctx, vsc.sqlSave, vsc.mutation, vsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (vsc *VerificationSessionCreate) SaveX(ctx context.Context) *VerificationSession {
	v, err := vsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vsc *VerificationSessionCreate) Exec(ctx context.Context) error {
	_, err := vsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vsc *VerificationSessionCreate) ExecX(ctx context.Context) {
	if err := vsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (vsc *VerificationSessionCreate) defaults() {
	if _, ok := vsc.mutation.ID(); !ok {
		v := verificationsession.DefaultID()
		vsc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (vsc *VerificationSessionCreate) check() error {
	if _, ok := vsc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VerificationSession.user_id"`)}
	}
	if _, ok := vsc.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "VerificationSession.session"`)}
	}
	return nil
}

func (vsc *VerificationSessionCreate) sqlSave(ctx context.Context) (*VerificationSession, error) {
	if err := vsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := vsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected VerificationSession.ID type: %T", _spec.ID.Value)
		}
	}
	vsc.mutation.id = &_node.ID
	vsc.mutation.done = true
	return _node, nil
}

func (vsc *VerificationSessionCreate) createSpec() (*VerificationSession, *sqlgraph.CreateSpec) {
	var (
		_node = &VerificationSession{config: vsc.config}
		_spec = sqlgraph.NewCreateSpec(verificationsession.Table, sqlgraph.NewFieldSpec(verificationsession.FieldID, field.TypeString))
	)
	if id, ok := vsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if nodes := vsc.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   verificationsession.SessionTable,
			Columns: []string{verificationsession.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VerificationSessionCreateBulk is the builder for creating many VerificationSession entities in bulk.
type VerificationSessionCreateBulk struct {
	config
	err      error
	builders []*VerificationSessionCreate
}

// Save creates the VerificationSession entities in the database.
func (vscb *VerificationSessionCreateBulk) Save(ctx context.Context) ([]*VerificationSession, error) {
	if vscb.err != nil {
		return nil, vscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(vscb.builders))
	nodes := make([]*VerificationSession, len(vscb.builders))
	mutators := make([]Mutator, len(vscb.builders))
	for i := range vscb.builders {
		func(i int, root context.Context) {
			builder := vscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VerificationSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, vscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, vscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, vscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (vscb *VerificationSessionCreateBulk) SaveX(ctx context.Context) []*VerificationSession {
	v, err := vscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (vscb *VerificationSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := vscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vscb *VerificationSessionCreateBulk) ExecX(ctx context.Context) {
	if err := vscb.Exec(ctx); err != nil {
		panic(err)
	}
}
