// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// Publication is the predicate function for publication builders.
type Publication func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VerificationSession is the predicate function for verificationsession builders.
type VerificationSession func(*sql.Selector)
