// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// VerifySession is the predicate function for verifysession builders.
type VerifySession func(*sql.Selector)
